// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olwrgthvydukavmpfeiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sd3JndGh2eWR1a2F2bXBmZWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODg2MDksImV4cCI6MjA1MDU2NDYwOX0.yqHqLzG4TUUGGNdE9I9ciWMsjlWBatFM6CPPWIIkQqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);